# Autogenerated by devscripts/update-version.py

__version__ = '2025.03.32-tsg'

RELEASE_GIT_HEAD = '89d42b2a0af58bc26cb2051fc25f6f1d7bc57ab8'

VARIANT = None

UPDATE_HINT = None

CHANNEL = 'stable'

ORIGIN = 'yt-dlp/yt-dlp'

_pkg_version = '2025.03.31'
